setup:
  type: list
  default: "privacy,7443|staging-pm,9471|internal-processes,5535|amplify-prerelease,96446"

setup_fixed:
  type: list
  default: "product-guides, 7440|implementation-guides, 7441"
  description: |
    Each line should be in the format of "<code>section name</code>, <code>post id</code>".<br/> (e.g., product-guides, 7441)<br/>
    <ul>
    <li>The section name is the name of the section you want to display in the sidebar</li>
    <li>The post ID is the first number in its url, for from the url community.example.com/t/welcome-to-discourse/8/10, you would use <b>8</b> in the setting</li>
    </ul>

setupDetails:
  type: list
  default: ""
  description: |
    Each line should be in the format of "<code>slug</code>, <code>ID</code>".<br/> (e.g., front-reliability, 719)<br/>
    <ul>
    <li>The slug is the slug name from its url, for example if your topic is located at community.marfeel.com/t/front-reliability/7141/14, you would use <b>front-reliability</b></li>

    <li>The topic ID is the first number in its url, for from the url community.example.com/t/welcome-to-discourse/8/10, you would use <b>8</b> in the setting</li>

    </ul>
    <p>Note that for a user to be able to see the sidebar, they must be able to access the topic. A topic in a protected category will not be visible as a sidebar to all users. If you don't want a sidebar topic to appear in your topic details, you can unlist it.</p>

setup_by_category_id:
  type: list
  default: ""
  description: |
    Each line should be in the format of "<code>category id</code>, <code>ID</code>".<br/> (e.g., 58, 719)<br/>
    <ul>
    <li>The category id is the id from category url, for example if your category is located at community.marfeel.com/c/marfeel-docs/instrumentation/58, you would use <b>58</b></li>
    <li>The topic ID is the first number in its url, for from the url community.example.com/t/welcome-to-discourse/8/10, you would use <b>8</b> in the setting</li>
    </ul>
    <p>Note that for a user to be able to see the sidebar, they must be able to access the topic. A topic in a protected category will not be visible as a sidebar to all users. If you don't want a sidebar topic to appear in your topic list, you can unlist it.</p>

sidebar_side:
  default: left
  type: enum
  choices:
    - left
    - right

inherit_parent_sidebar:
  default: true
  type: bool

stick_on_scroll:
  default: false
  type: bool

icon_mappings:
  type: list
  default: "Platform, mrf-apps|Editorial, mrf-editorial|Audience, mrf-users|Engagement, mrf-heart|Subscriptions, mrf-subscriptions|Advertisement, mrf-comments-lines|Social, mrf-comments|Affiliation, mrf-shopping-bag|User settings, mrf-user-settings|SDKs, mrf-apps|Editorial metadata, mrf-apps|Multimedia, mrf-play|Experiences, mrf-map-pin|Data Exports, mrf-shuffle|Marfeel API, mrf-bolt|Organization settings, mrf-user-settings|Debugging, mrf-apps|Recommender, mrf-recommender|Amplify, mrf-amplify"
  description: |
    Each line should be in the format of "<code>Section Name, icon-identifier</code>".<br/> (e.g., Platform, mrf-apps)<br/>
    <ul>
    <li>The section name should match exactly as it appears in your content</li>
    <li>The icon identifier corresponds to the icon you want to display</li>
    </ul>
  client: true
